name: assist_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
